
/*USE persons;
CREATE TABLE PERSONS
(
GITID NVARCHAR(20) NOT NULL,
TELID NVARCHAR(20) NOT NULL,
SURNAME NVARCHAR(20) NOT NULL,
NAMEP NVARCHAR(20) NOT NULL,
FATHER_NAME NVARCHAR(20) NOT NULL,
GROUPP NVARCHAR(20) NOT NULL,
STUDENT BIT DEFAULT 0,
LEHRER BIT DEFAULT 0,
ADMINP BIT DEFAULT 0
)
INSERT PERSONS VALUES ('123456', '123132', 'Аметов', 'Кемран', 'Ленверович', '231-б-о-231(2)', 1, 0, 0) 
USE PERSONS
SELECT * FROM PERSONS
*/
USE persons;
/*CREATE TABLE MENSCHEN (
    GITID NVARCHAR(20) NOT NULL,
	TELID NVARCHAR(20) NOT NULL,
	SURNAME NVARCHAR(20) NOT NULL,
	NAMEP NVARCHAR(20) NOT NULL,
	FATHER_NAME NVARCHAR(20) NOT NULL,
	GROUPP NVARCHAR(20) NOT NULL,
	STUDENT INT DEFAULT 0,
	LEHRER INT DEFAULT 0,
	ADMINP INT DEFAULT 0
);*/
/*INSERT INTO MENSCHEN VALUES ('123456', '123132', 'Аметов', 'Кемран', 'Ленверович', 'ПИ-б-о-231(2)', 1, 0, 1);*/
SELECT * FROM MENSCHEN;